name: twitter_clone
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  any_link_preview: ^3.0.1
  appwrite: ^9.0.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  fpdart: ^1.1.0
  image_picker: ^0.8.6+1
  like_button: ^2.0.5
  timeago: ^3.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
